framework:
  cache:
    prefix_seed: merashop
    app: cache.adapter.redis
    system: cache.adapter.redis
    default_redis_provider: '%env(resolve:REDIS_URL)%'

    pools:
      identity_access.token_blacklist:
        adapter: cache.adapter.redis
        default_lifetime: 3600
