doctrine:
  dbal:
    types:
      outbox_email_status: App\EmailSender\Infrastructure\Persistence\Doctrine\Type\OutboxEmail\StatusType
      outbox_email_driver: App\EmailSender\Infrastructure\Persistence\Doctrine\Type\OutboxEmail\DriverType
      refresh_token_account_type: App\IdentityAccess\Infrastructure\Persistence\Doctrine\Type\RefreshToken\AccountType
    default_connection: identity_access
    connections:
      users:
        url: '%env(resolve:DATABASE_URL_USERS)%'
        profiling_collect_backtrace: '%kernel.debug%'
      email_sender:
        url: '%env(resolve:DATABASE_URL_EMAIL_SENDER)%'
        profiling_collect_backtrace: '%kernel.debug%'
        mapping_types:
          outbox_email_status: outbox_email_status
          outbox_email_driver: outbox_email_driver
      identity_access:
        url: '%env(resolve:DATABASE_URL_IDENTITY_ACCESS)%'
        profiling_collect_backtrace: '%kernel.debug%'
        mapping_types:
          refresh_token_account_type: refresh_token_account_type
  orm:
    controller_resolver:
      auto_mapping: false
    entity_managers:
      users:
        connection: users
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Users:
            type: attribute
            is_bundle: false
            dir: '%kernel.project_dir%/src/Users/Infrastructure/Persistence/Doctrine/Entity'
            prefix: 'App\Users\Infrastructure\Persistence\Doctrine\Entity'
            alias: Users
      email_sender:
        connection: email_sender
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          EmailSender:
            type: attribute
            is_bundle: false
            dir: '%kernel.project_dir%/src/EmailSender/Infrastructure/Persistence/Doctrine/Entity'
            prefix: 'App\EmailSender\Infrastructure\Persistence\Doctrine\Entity'
            alias: EmailSender
      identity_access:
        connection: identity_access
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          IdentityAccess:
            type: attribute
            is_bundle: false
            dir: '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Persistence/Doctrine/Entity'
            prefix: 'App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity'
            alias: IdentityAccess

when@test:

when@prod:
  doctrine:
    orm:
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
