framework:
  messenger:
    # need to define each failure_transport separately
    failure_transport: null

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # Catalog Module
      catalog_outbox:
        dsn: 'doctrine://catalog'
        failure_transport: catalog_failed
        options: &catalog_options
          table_name: 'catalog_messages'
          queue_name: !php/enum App\Catalog\Domain\Enum\MessengerQueueEnum::Outbox->value
          auto_setup: false
      catalog_failed:
        dsn: 'doctrine://catalog'
        options:
          <<: *catalog_options
          queue_name: !php/enum App\Catalog\Domain\Enum\MessengerQueueEnum::Failed->value
      catalog_internal:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        failure_transport: amqp_failed
        options:
          exchange:
            name: 'catalog.internal'
            type: 'direct'
          queues:
            email_processor:
              binding_keys:
                - !php/enum App\Catalog\Domain\Enum\CatalogEventNameEnum::CategoryMoved->value
      # Customer Module
      customer_external:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        failure_transport: amqp_failed
        options:
          auto_setup: true
          confirm_timeout: 5
          exchange:
            name: 'domain_events'
            type: 'topic'
          queues:
            customer_module:
              binding_keys:
                - !php/enum App\Shared\Domain\Enum\SharedEventNameEnum::UserRegistered->value
      # EmailSender Module
      email_sender_external:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        failure_transport: amqp_failed
        options:
          auto_setup: true
          confirm_timeout: 5
          exchange:
            name: 'domain_events'
            type: 'topic'
          queues:
            email_sender_module:
              binding_keys:
                - !php/enum App\Shared\Domain\Enum\SharedEventNameEnum::UserRegistered->value
      email_sender_internal:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        failure_transport: amqp_failed
        options:
          exchange:
            name: 'email_sender.internal'
            type: 'direct'
          queues:
            email_processor:
              binding_keys:
                - !php/enum App\EmailSender\Domain\Enum\EmailSenderEventNameEnum::EmailProcessor->value
      # Identity Access Module
      identity_access_outbox:
        dsn: 'doctrine://identity_access'
        failure_transport: identity_access_failed
        options: &identity_access_options
          table_name: 'identity_access_messages'
          queue_name: !php/enum App\IdentityAccess\Domain\Enum\MessengerQueueEnum::Outbox->value
          auto_setup: false
      identity_access_failed:
        dsn: 'doctrine://identity_access'
        options:
          <<: *identity_access_options
          queue_name: !php/enum App\IdentityAccess\Domain\Enum\MessengerQueueEnum::Failed->value
      # Base
      amqp_events:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        failure_transport: amqp_failed
        options:
          auto_setup: true
          confirm_timeout: 5
          exchange:
            name: 'domain_events'
            type: 'topic'
      amqp_failed:
        dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
        options:
          auto_setup: true
          exchange:
            name: 'failed_events'
            type: 'fanout'
          queues:
            failed_events: ~

    default_bus: command.bus

    buses:
      command.bus:
        middleware:
          - doctrine_transaction: [catalog]
          - doctrine_transaction: [customer]
          - doctrine_transaction: [identity_access]
          - doctrine_transaction: [email_sender]
          - 'App\Shared\Infrastructure\Bus\TraceId\TraceIdMiddleware'
          - 'App\Shared\Infrastructure\Bus\Middleware\EventRoutingKeyMiddleware'
      query.bus:
      event.bus:
        middleware:
          - 'App\Shared\Infrastructure\Bus\TraceId\TraceIdMiddleware'
          - 'App\Shared\Infrastructure\Bus\Middleware\EventRoutingKeyMiddleware'
      messenger.bus.default: [ ]

    routing:
      # Shared
      App\Shared\Domain\Event\UserRegisteredSharedEvent: identity_access_outbox
      # Catalog Module
      App\Catalog\Domain\Event\CategoryMovedDomainEvent: catalog_outbox
      # EmailSender Module
      App\EmailSender\Application\Command\SendOutboxEmail\SendOutboxEmailCommand: email_sender_internal
