framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(DOCTRINE_MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            amqp:
              dsn: '%env(AMQP_MESSENGER_TRANSPORT_DSN)%'
              options:
                auto_setup: true
                confirm_timeout: 5
            # sync: 'sync://'

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                  - doctrine_transaction
            query.bus:
            event.bus:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
