twig:
    file_name_pattern: '*.twig'
    paths:
      '%kernel.project_dir%/src/EmailSender/Infrastructure/Resources/templates/twig': EmailSender

when@test:
    twig:
        strict_variables: true
