x-queue-worker-defaults: &queue-worker-defaults
  image: merashop/app:latest
  depends_on:
    pgsql:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
  deploy:
    mode: replicated
    replicas: 1
    update_config:
      parallelism: 1
      failure_action: rollback
      order: start-first
    rollback_config:
      parallelism: 1
      order: start-first
      failure_action: continue
    resources:
      limits:
        cpus: '0.35'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M
  environment:
    APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
    PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
  healthcheck:
    test: [ "CMD-SHELL", "php -r \"echo 'php is alive';\" || exit 1" ]
    retries: 3
    timeout: 5s
  networks:
    - merashop-network
  volumes:
    - ./:/var/www

services:
  pgsql:
    image: postgres:18-alpine3.21
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_IDENTITY_ACCESS}
      POSTGRES_DB_CUSTOMER: ${POSTGRES_DB_CUSTOMER}
      POSTGRES_DB_IDENTITY_ACCESS: ${POSTGRES_DB_IDENTITY_ACCESS}
      POSTGRES_DB_EMAIL_SENDER: ${POSTGRES_DB_EMAIL_SENDER}
      POSTGRES_DB_CATALOG: ${POSTGRES_DB_CATALOG}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB_IDENTITY_ACCESS}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.33'
          memory: 350M
    networks:
      - merashop-network
    ports:
      - ${FORWARD_DB_PORT}:5432
    volumes:
      - pgsql:/var/lib/postgresql/data
      - ./docker/pgsql/shell/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  pgsql-test:
    image: postgres:18-alpine3.21
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_IDENTITY_ACCESS}
      POSTGRES_DB_CUSTOMER: ${POSTGRES_DB_CUSTOMER}
      POSTGRES_DB_IDENTITY_ACCESS: ${POSTGRES_DB_IDENTITY_ACCESS}
      POSTGRES_DB_EMAIL_SENDER: ${POSTGRES_DB_EMAIL_SENDER}
      POSTGRES_DB_CATALOG: ${POSTGRES_DB_CATALOG}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB_IDENTITY_ACCESS}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.33'
          memory: 350M
    networks:
      - merashop-network
    ports:
      - ${FORWARD_TEST_DB_PORT}:5432
    volumes:
      - pgsql-test:/var/lib/postgresql/data
      - ./docker/pgsql/shell/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - merashop-network
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data

  redis-test:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes --maxmemory 64mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 32M
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - merashop-network
    ports:
      - "${FORWARD_TEST_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-test:/data

  nginx:
    image: merashop/nginx:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first
        failure_action: continue
      resources:
        limits:
          cpus: '0.25'
          memory: 125M
        reservations:
          cpus: '0.25'
          memory: 100M
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      PHP_CGI_PASS: ${PHP_CGI_PASS}
      APP_WEB_DOMAIN: ${APP_WEB_DOMAIN}
      APP_API_DOMAIN: ${APP_API_DOMAIN}
      APP_ADMIN_API_DOMAIN: ${APP_ADMIN_API_DOMAIN}
      APP_SOURCES_DOMAIN: ${APP_SOURCES_DOMAIN}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/health_check || exit 1" ]
      retries: 3
      timeout: 5s
    networks:
      - merashop-network
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_SECURED_PORT:-443}:443
    volumes:
      - ./docker/nginx/etc/ssl:/etc/nginx/ssl
    depends_on:
      - app

  app:
    image: merashop/app:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first
        failure_action: continue
      resources:
        limits:
          cpus: '0.75'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 350M
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      PHP_IDE_CONFIG: serverName=Docker
      STATIC_PHP_FPM_POOL_WORKERS: 5
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      PHP_CGI_PASS: ${PHP_CGI_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "./docker/app/shell/php-fpm-healthcheck.sh || exit 1" ]
      retries: 3
      timeout: 5s
    networks:
      - merashop-network
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
      - ./docker/app/php/conf.d/zzz-settings-override-local.ini:/usr/local/etc/php/conf.d/zzz-settings-override.ini
    working_dir: /var/www

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - merashop-network
    ports:
      - ${RABBITMQ_FORWARD_PORT}:5672
      - ${RABBITMQ_DASHBOARD_FORWARD_PORT}:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  elasticsearch:
    image: elastic/elasticsearch:9.2.3
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      node.name: es01
      discovery.type: 'single-node'
      xpack.security.enabled: ${ELASTIC_XPACK_SECURITY_ENABLED}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - merashop-network
    ports:
      - ${ELASTIC_FORWARD_PORT}:9200
    volumes:
      -  elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: elastic/kibana:9.2.3
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      ELASTICSEARCH_HOSTS: ${KIBANA_ELASTIC_HOST}
      ELASTICSEARCH_USERNAME: ${KIBANA_USERNAME}
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    networks:
      - merashop-network
    ports:
      - ${KIBANA_FOWARD_PORT}:5601

  filebeat:
    image: merashop/filebeat:latest
    user: root
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      ELASTIC_HOSTS: ${ELASTIC_HOSTS}
      ELASTIC_USER: ${ELASTIC_USER}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_HOST: ${KIBANA_HOST}
    networks:
      - merashop-network
    volumes:
      - ./var/log:/var/log/app:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch

  catalog-outbox-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: catalog_outbox

  catalog-internal-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: catalog_internal

  customer-external-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: customer_external
      MESSENGER_QUEUES: customer_module

  email-sender-external-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: email_sender_external
      MESSENGER_QUEUES: email_sender_module

  email-sender-internal-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: email_sender_internal
      MESSENGER_QUEUES: email_processor

  email-sender-sheduler-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: scheduler
      MESSENGER_TRANSPORT: scheduler_email_sender

  identity-access-outbox-queue-worker:
    <<: *queue-worker-defaults
    environment:
      PLATFORM_ARCHITECTURE: ${PLATFORM_ARCHITECTURE}
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV}
      WAIT_RABBITMQ: true
      WORKER_TYPE: queue
      MESSENGER_TRANSPORT: identity_access_outbox

networks:
  merashop-network:

volumes:
  pgsql:
    driver: local
  pgsql-test:
    driver: local
  redis:
    driver: local
  redis-test:
    driver: local
  rabbitmq:
    driver: local
  elasticsearch:
    driver: local
