x-queue-worker-defaults: &queue-worker-defaults-override
  platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
  pull_policy: never
  restart: on-failure

services:
  pgsql:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  pgsql-test:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  redis:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  redis-test:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  nginx:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      tags:
        - merashop/nginx:latest
    depends_on:
      - app

  app:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: ${APP_RUNTIME_ENV}
      tags:
        - merashop/app:latest
    depends_on:
      - pgsql
      - redis
    restart: on-failure

  rabbitmq:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  elasticsearch:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  kibana:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}

  filebeat:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: ./docker/filebeat
      dockerfile: ./Dockerfile
      tags:
        - merashop/filebeat:latest

  catalog-outbox-queue-worker:
    <<: *queue-worker-defaults-override

  catalog-internal-queue-worker:
    <<: *queue-worker-defaults-override

  customer-external-queue-worker:
    <<: *queue-worker-defaults-override

  email-sender-external-queue-worker:
    <<: *queue-worker-defaults-override

  email-sender-internal-queue-worker:
    <<: *queue-worker-defaults-override

  email-sender-sheduler-worker:
    <<: *queue-worker-defaults-override

  identity-access-outbox-queue-worker:
    <<: *queue-worker-defaults-override
