
services:
  nginx:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      tags:
        - merashop/nginx:latest
    depends_on:
      - app

  app:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: ${APP_RUNTIME_ENV}
      tags:
        - merashop/app:latest
    depends_on:
      - pgsql
    restart: on-failure

  filebeat:
    platform: ${PLATFORM_ARCHITECTURE:-linux/amd64}
    build:
      context: ./docker/filebeat
      dockerfile: ./Dockerfile
      tags:
        - merashop/filebeat:latest
