filebeat:
  inputs:
    - type: filestream
      id: symfony-logs
      enabled: true
      paths:
        - /var/log/app/*.log
      parsers:
        - ndjson:
            keys_under_root: true
            add_error_key: true
            overwrite_keys: true

output:
  elasticsearch:
    hosts: ["${ELASTIC_HOSTS:elasticsearch:9200}"]
    username: "${ELASTIC_USER:elastic}"
    password: "${ELASTIC_PASSWORD:}"

logging:
  level: info

setup:
  template:
    enabled: true
    json:
      enabled: true
      path: "template.json"
      name: "filebeat"
  ilm:
    enabled: true
    policy_name: "filebeat"
  kibana:
    host: "${KIBANA_HOST:kibana:5601}"
