<?php

declare(strict_types=1);

namespace App\EmailSender\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251221134704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create outbox email table for email sender module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE outbox_email_status AS ENUM ('created', 'processing', 'sent', 'failed', 'failed_permanently')");
        $this->addSql("CREATE TYPE outbox_email_driver AS ENUM ('log', 'smtp')");

        $this->addSql(
            'CREATE TABLE outbox_emails (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            status outbox_email_status NOT NULL DEFAULT \'created\',
            driver outbox_email_driver NOT NULL,
            "from" VARCHAR(255) NOT NULL,
            from_name VARCHAR(255) DEFAULT NULL,
            "to" VARCHAR(255) NOT NULL,
            subject VARCHAR(255) NOT NULL,
            body TEXT NOT NULL,
            payload JSONB DEFAULT NULL,
            attempts INT NOT NULL DEFAULT 0,
            scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            error_message TEXT DEFAULT NULL,
            trace_id UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );

        $this->addSql(
            'CREATE INDEX idx_outbox_process
                ON outbox_emails (status, scheduled_at)
                WHERE (
                    (status = \'created\'::outbox_email_status)
                        OR (status = \'failed\'::outbox_email_status)
                    )'
        );
        $this->addSql('CREATE INDEX idx_outbox_emails_trace_id ON outbox_emails (trace_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE outbox_emails');
        $this->addSql('DROP TYPE outbox_email_status');
        $this->addSql('DROP TYPE outbox_email_driver');
    }
}
