<?php

declare(strict_types=1);

namespace App\EmailSender\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251221134704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create outbox email table for email sender module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE outbox_email_status AS ENUM ('created', 'processing', 'processed', 'failed', 'sent')");
        $this->addSql("CREATE TYPE outbox_email_driver AS ENUM ('log', 'smtp')");

        $this->addSql(
            'CREATE TABLE email_sender_outbox_email (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                status outbox_email_status NOT NULL,
                driver outbox_email_driver NOT NULL,
                subject VARCHAR(255) NOT NULL,
                "from" VARCHAR(256) NOT NULL,
                from_name VARCHAR(255) NOT NULL,
                "to" VARCHAR(256) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE email_sender_outbox_email');
    }
}
