<?php

declare(strict_types=1);

namespace App\Tests\Customer\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\Customer\Domain\Entity\CustomerProfile;
use App\Customer\Infrastructure\Persistence\Doctrine\Entity\OrmCustomerProfile;
use App\Customer\Infrastructure\Persistence\Doctrine\Mapper\CustomerProfileMapper;
use App\Tests\Customer\Support\CustomerProfileMother;
use App\Tests\Customer\Support\Traits\CustomerEntityManagerTrait;
use App\Tests\Shared\Support\Traits\ValueObjectAssertionTrait;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class CustomerProfileMapperTest extends KernelTestCase
{
    use CustomerEntityManagerTrait;
    use ValueObjectAssertionTrait;

    private EntityManagerInterface $em;
    private CustomerProfileMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getCustomerEntityManager();
        $this->mapper = new CustomerProfileMapper();
    }

    #[DataProvider('customerProfileStateProvider')]
    public function testItSuccessfullyPerformsRoundTrip(CustomerProfile $domainCustomerProfile): void
    {
        $ormCustomerProfile = $this->mapper->toDoctrineOrm($domainCustomerProfile);

        self::assertNull($ormCustomerProfile->id);
        self::assertSame($domainCustomerProfile->getFirstName()?->value(), $ormCustomerProfile->firstName);
        self::assertSame($domainCustomerProfile->getLastName()?->value(), $ormCustomerProfile->lastName);
        self::assertSame($domainCustomerProfile->getPhoneNumber()?->value(), $ormCustomerProfile->phoneNumber);

        $this->em->persist($ormCustomerProfile);
        $this->em->flush();

        $generatedId = $ormCustomerProfile->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmCustomerProfile::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainCustomerProfile->getUserUlid()->equals($restoredDomain->getUserUlid()));
        $this->assertVoEqualsOrNull($domainCustomerProfile->getFirstName(), $restoredDomain->getFirstName());
        $this->assertVoEqualsOrNull($domainCustomerProfile->getLastName(), $restoredDomain->getLastName());
        $this->assertVoEqualsOrNull($domainCustomerProfile->getPhoneNumber(), $restoredDomain->getPhoneNumber());
    }

    public static function customerProfileStateProvider(): iterable
    {
        yield 'just created' => [CustomerProfileMother::createWithData()];
        yield 'completed' => [CustomerProfileMother::createWithData(firstName: 'John', lastName: 'Doe', phoneNumber: '+380998877666')];
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainCustomerProfile = CustomerProfileMother::createWithData(
            firstName: 'John',
            lastName: 'Doe',
            phoneNumber: '+380998877666',
        );
        $ormCustomerProfile = new OrmCustomerProfile();
        $ormCustomerProfile->firstName = 'old first name';
        $ormCustomerProfile->lastName = 'old last name';
        $ormCustomerProfile->phoneNumber = 'old phone number';

        $this->mapper->mapToExistingOrm($domainCustomerProfile, $ormCustomerProfile);

        self::assertSame($domainCustomerProfile->getFirstName()->value(), $ormCustomerProfile->firstName);
        self::assertSame($domainCustomerProfile->getLastName()->value(), $ormCustomerProfile->lastName);
        self::assertSame($domainCustomerProfile->getPhoneNumber()->value(), $ormCustomerProfile->phoneNumber);
        self::assertNull($ormCustomerProfile->id);
        self::assertNull($ormCustomerProfile->userUlid);
    }
}
