<?php

declare(strict_types=1);

namespace App\Users\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251221104730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users table for users module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE users_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                ulid UUID NOT NULL,
                first_name VARCHAR(64) NOT NULL,
                last_name VARCHAR(64) NOT NULL,
                email VARCHAR(256) NOT NULL,
                phone_number VARCHAR(15) DEFAULT NULL,
                password VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_421A9847C288C859 ON users_user (ulid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users_user');
    }
}
