<?php

declare(strict_types=1);

namespace App\Tests\EmailSender\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\EmailSender\Domain\Entity\OutboxEmail;
use App\EmailSender\Domain\Enum\OutboxEmail\DriverEnum;
use App\EmailSender\Domain\Enum\OutboxEmail\StatusEnum;
use App\EmailSender\Infrastructure\Persistence\Doctrine\Entity\OrmOutboxEmail;
use App\EmailSender\Infrastructure\Persistence\Doctrine\Mapper\OutboxEmailMapper;
use App\Shared\Domain\ValueObject\TraceId;
use App\Tests\EmailSender\Support\OutboxEmailMother;
use App\Tests\EmailSender\Support\Traits\EmailSenderEntityManagerTrait;
use App\Tests\Shared\Support\Traits\ValueObjectAssertionTrait;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Clock\MockClock;

class OutboxEmailMapperTest extends KernelTestCase
{
    use EmailSenderEntityManagerTrait;
    use ValueObjectAssertionTrait;

    private EntityManagerInterface $em;
    private OutboxEmailMapper $mapper;

    protected function setUp(): void
    {
        $this->em = $this->getEmailSenderEntityManager();
        $this->mapper = new OutboxEmailMapper();
    }

    #[DataProvider('outboxEmailStateProvider')]
    public function testItSuccessfullyPerformsRoundTrip(OutboxEmail $domainOutboxEmail): void
    {
        $ormOutboxEmail = $this->mapper->toDoctrineOrm($domainOutboxEmail);

        self::assertNull($ormOutboxEmail->id);
        self::assertSame($domainOutboxEmail->getStatus()->value(), $ormOutboxEmail->status);
        self::assertSame($domainOutboxEmail->getDriver()->value(), $ormOutboxEmail->driver);
        self::assertSame($domainOutboxEmail->getFrom()->value(), $ormOutboxEmail->from);
        self::assertSame($domainOutboxEmail->getFromName()->value(), $ormOutboxEmail->fromName);
        self::assertSame($domainOutboxEmail->getTo()->value(), $ormOutboxEmail->to);
        self::assertSame($domainOutboxEmail->getSubject()->value(), $ormOutboxEmail->subject);
        self::assertSame($domainOutboxEmail->getBody()->value(), $ormOutboxEmail->body);
        self::assertSame($domainOutboxEmail->getPayload()?->value(), $ormOutboxEmail->payload);
        self::assertSame($domainOutboxEmail->getAttempts()->value(), $ormOutboxEmail->attempts);
        self::assertSame($domainOutboxEmail->getTraceId()?->value(), $ormOutboxEmail->traceId);
        self::assertSame($domainOutboxEmail->getScheduledAt()?->value(), $ormOutboxEmail->scheduledAt);
        self::assertSame($domainOutboxEmail->getLockedAt()?->value(), $ormOutboxEmail->lockedAt);
        self::assertSame($domainOutboxEmail->getErrorMessage()?->value(), $ormOutboxEmail->errorMessage);

        $this->em->persist($ormOutboxEmail);
        $this->em->flush();

        $generatedId = $ormOutboxEmail->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmOutboxEmail::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($restoredDomain->getStatus()->equals($domainOutboxEmail->getStatus()));
        self::assertTrue($restoredDomain->getDriver()->equals($domainOutboxEmail->getDriver()));
        self::assertTrue($restoredDomain->getFrom()->equals($domainOutboxEmail->getFrom()));
        self::assertTrue($restoredDomain->getFromName()->equals($domainOutboxEmail->getFromName()));
        self::assertTrue($restoredDomain->getTo()->equals($domainOutboxEmail->getTo()));
        self::assertTrue($restoredDomain->getSubject()->equals($domainOutboxEmail->getSubject()));
        self::assertTrue($restoredDomain->getBody()->equals($domainOutboxEmail->getBody()));
        $this->assertVoEqualsOrNull($domainOutboxEmail->getPayload(), $restoredDomain->getPayload());
        self::assertTrue($restoredDomain->getAttempts()->equals($domainOutboxEmail->getAttempts()));
        $this->assertVoEqualsOrNull($domainOutboxEmail->getTraceId(), $restoredDomain->getTraceId());
        $this->assertVoEqualsOrNull($domainOutboxEmail->getScheduledAt(), $restoredDomain->getScheduledAt());
        $this->assertVoEqualsOrNull($domainOutboxEmail->getLockedAt(), $restoredDomain->getLockedAt());
        $this->assertVoEqualsOrNull($domainOutboxEmail->getErrorMessage(), $restoredDomain->getErrorMessage());
    }

    public static function outboxEmailStateProvider(): iterable
    {
        $clock = new MockClock('2024-01-01 10:00:00');

        yield 'State: Created (clean)' => [
            OutboxEmailMother::createWithData(status: StatusEnum::Created),
        ];

        yield 'State: Failed (with error and schedule)' => [
            OutboxEmailMother::createWithData(
                status: StatusEnum::Failed,
                attempts: 3,
                scheduledAt: $clock->now()->modify('+1 hour'),
                errorMessage: 'Connection timeout'
            ),
        ];

        yield 'State: Processing (locked)' => [
            OutboxEmailMother::createWithData(
                status: StatusEnum::Processing,
                lockedAt: $clock->now()
            ),
        ];
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $clock = new MockClock('2024-01-01 10:00:00');

        $domainOutboxEmail = OutboxEmailMother::createWithData(
            status: StatusEnum::Failed,
            driver: DriverEnum::Log,
            attempts: 1,
            traceId: TraceId::fromString('01946393-271d-799d-8f2e-062e2467d018'),
            scheduledAt: $clock->now()->modify('+1 minute'),
            errorMessage: 'Error message',
        );

        $ormOutboxEmail = new OrmOutboxEmail();
        $ormOutboxEmail->status = StatusEnum::Processing;
        $ormOutboxEmail->attempts = 0;
        $ormOutboxEmail->scheduledAt = null;
        $ormOutboxEmail->lockedAt = $clock->now();
        $ormOutboxEmail->errorMessage = null;

        $this->mapper->mapToExistingOrm($domainOutboxEmail, $ormOutboxEmail);

        self::assertSame($domainOutboxEmail->getStatus()->value(), $ormOutboxEmail->status);
        self::assertSame($domainOutboxEmail->getAttempts()->value(), $ormOutboxEmail->attempts);
        self::assertSame($domainOutboxEmail->getScheduledAt()?->value(), $ormOutboxEmail->scheduledAt);
        self::assertSame($domainOutboxEmail->getLockedAt()?->value(), $ormOutboxEmail->lockedAt);
        self::assertSame($domainOutboxEmail->getErrorMessage()?->value(), $ormOutboxEmail->errorMessage);

        self::assertNull($ormOutboxEmail->driver);
        self::assertNull($ormOutboxEmail->from);
        self::assertNull($ormOutboxEmail->fromName);
        self::assertNull($ormOutboxEmail->to);
        self::assertNull($ormOutboxEmail->subject);
        self::assertNull($ormOutboxEmail->body);
        self::assertNull($ormOutboxEmail->payload);
        self::assertNull($ormOutboxEmail->traceId);
    }
}
