shared.public.web:
  resource:
    path: ../Web/Controller/
    namespace: App\Shared\Presentation\Http\Web\Controller
  type: attribute

shared.public.api.v1:
  resource:
    path: ../ApiVersion1/Controller/
    namespace: App\Shared\Presentation\Http\ApiVersion1\Controller
  type: attribute
  prefix: /api/v1/
