<?php

declare(strict_types=1);

namespace App\Tests\IdentityAccess\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\IdentityAccess\Domain\Enum\AdminAccount\StatusEnum;
use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity\OrmAdminAccount;
use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Mapper\AdminAccountMapper;
use App\Tests\IdentityAccess\Support\AdminAccountMother;
use App\Tests\IdentityAccess\Support\Traits\IdentityAccessEntityManagerTrait;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class AdminAccountMapperTest extends KernelTestCase
{
    use IdentityAccessEntityManagerTrait;

    private EntityManagerInterface $em;
    private AdminAccountMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getIdentityAccessEntityManager();
        $this->mapper = new AdminAccountMapper();
    }

    #[DataProvider('adminAccountProvider')]
    public function testItSuccessfullyPerformsRoundTrip(
        string $email,
        StatusEnum $status,
        ?DateTimeImmutable $passwordChangedAt,
    ): void {
        $domainAdmin = AdminAccountMother::createWithData(
            email: $email,
            status: $status,
            passwordChangedAt: $passwordChangedAt
        );

        $ormAdmin = $this->mapper->toDoctrineOrm($domainAdmin);

        self::assertNull($ormAdmin->id);
        self::assertSame($domainAdmin->getUlid()->value(), $ormAdmin->ulid);
        self::assertSame($email, $ormAdmin->email);
        self::assertSame($domainAdmin->getPasswordHash()->value(), $ormAdmin->passwordHash);
        self::assertIsArray($ormAdmin->roles);
        self::assertSame($domainAdmin->getRoles()->toStrings(), $ormAdmin->roles);
        self::assertSame($status, $ormAdmin->status);
        self::assertSame($passwordChangedAt, $ormAdmin->passwordChangedAt);

        $this->em->persist($ormAdmin);
        $this->em->flush();

        $generatedId = $ormAdmin->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmAdminAccount::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainAdmin->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainAdmin->getEmail()->equals($restoredDomain->getEmail()));
        self::assertTrue($domainAdmin->getPasswordHash()->equals($restoredDomain->getPasswordHash()));
        self::assertIsArray($restoredDomain->getRoles()->toStrings());
        self::assertTrue($domainAdmin->getRoles()->equals($restoredDomain->getRoles()));
        self::assertTrue($domainAdmin->getStatus()->equals($restoredDomain->getStatus()));
        if ($passwordChangedAt) {
            self::assertTrue($domainAdmin->getPasswordChangedAt()?->equals($restoredDomain->getPasswordChangedAt()));
        } else {
            self::assertNull($restoredDomain->getPasswordChangedAt());
        }
    }

    public static function adminAccountProvider(): iterable
    {
        yield 'active admin without password change date' => [
            'active.admin.test.mapper@test.com',
            StatusEnum::Active,
            null,
        ];
        yield 'blocked admin with password change date' => [
            'blocked.admin.test.mapper@test.com',
            StatusEnum::Blocked,
            new DateTimeImmutable('2023-10-27 10:00:00'),
        ];
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainAdmin = AdminAccountMother::createWithData(roles: ['ROLE_ADMIN']);
        $ormAdmin = new OrmAdminAccount();
        $ormAdmin->roles = ['ROLE_OLD'];
        $ormAdmin->passwordHash = 'old_hash';
        $ormAdmin->passwordChangedAt = new DateTimeImmutable('-2 years');
        $ormAdmin->status = StatusEnum::OnVacation;

        $this->mapper->mapToExistingOrm($domainAdmin, $ormAdmin);

        self::assertSame($domainAdmin->getRoles()->toStrings(), $ormAdmin->roles);
        self::assertSame($domainAdmin->getPasswordHash()->value(), $ormAdmin->passwordHash);
        self::assertSame($domainAdmin->getStatus()->value(), $ormAdmin->status);
        self::assertSame($domainAdmin->getPasswordChangedAt()?->value(), $ormAdmin->passwordChangedAt);
        self::assertNull($ormAdmin->id);
        self::assertNull($ormAdmin->ulid);
        self::assertNull($ormAdmin->email);
    }
}
