<?php

declare(strict_types=1);

namespace App\Tests\IdentityAccess\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity\OrmModuleAccount;
use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Mapper\ModuleAccountMapper;
use App\Tests\IdentityAccess\Support\ModuleAccountMother;
use App\Tests\IdentityAccess\Support\Traits\IdentityAccessEntityManagerTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class ModuleAccountMapperTest extends KernelTestCase
{
    use IdentityAccessEntityManagerTrait;

    private EntityManagerInterface $em;
    private ModuleAccountMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getIdentityAccessEntityManager();
        $this->mapper = new ModuleAccountMapper();
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainModule = ModuleAccountMother::createWithData(clientId: 'module_a_client_id');

        $ormModule = $this->mapper->toDoctrineOrm($domainModule);

        self::assertNull($ormModule->id);
        self::assertSame($domainModule->getUlid()->value(), $ormModule->ulid);
        self::assertSame($domainModule->getClientId()->value(), $ormModule->clientId);
        self::assertSame($domainModule->getClientSecret()->value(), $ormModule->clientSecret);
        self::assertIsArray($ormModule->scopes);
        self::assertSame($domainModule->getScopes()->toStrings(), $ormModule->scopes);

        $this->em->persist($ormModule);
        $this->em->flush();

        $generatedId = $ormModule->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmModuleAccount::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainModule->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainModule->getClientId()->equals($restoredDomain->getClientId()));
        self::assertTrue($domainModule->getClientSecret()->equals($restoredDomain->getClientSecret()));
        self::assertIsArray($restoredDomain->getScopes()->toStrings());
        self::assertTrue($domainModule->getScopes()->equals($restoredDomain->getScopes()));
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainModule = ModuleAccountMother::createWithData(scopes: ['scope_module']);
        $ormModule = new OrmModuleAccount();
        $ormModule->scopes = ['scope_old'];

        $this->mapper->mapToExistingOrm($domainModule, $ormModule);

        self::assertEquals($domainModule->getScopes()->toStrings(), $ormModule->scopes);
        self::assertNull($ormModule->id);
        self::assertNull($ormModule->ulid);
        self::assertNull($ormModule->clientId);
        self::assertNull($ormModule->clientSecret);
    }
}
