<?php

declare(strict_types=1);

namespace App\Tests\IdentityAccess\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity\OrmRefreshToken;
use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Mapper\RefreshTokenMapper;
use App\Tests\IdentityAccess\Support\RefreshTokenMother;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class RefreshTokenMapperTest extends KernelTestCase
{
    private EntityManagerInterface $em;
    private RefreshTokenMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = self::getContainer()->get('doctrine')->getManager('identity_access');
        $this->mapper = new RefreshTokenMapper();
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainToken = RefreshTokenMother::createWithData();

        $ormToken = $this->mapper->toDoctrineOrm($domainToken);

        self::assertNull($ormToken->id);
        self::assertSame($domainToken->getTokenHash()->value(), $ormToken->token);
        self::assertSame($domainToken->getAccountUlid()->value(), $ormToken->accountUlid);
        self::assertSame($domainToken->getAccountType()->value(), $ormToken->accountType);
        self::assertSame($domainToken->getExpiresAt()->value(), $ormToken->expiresAt);

        $this->em->persist($ormToken);
        $this->em->flush();

        $generatedId = $ormToken->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmRefreshToken::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainToken->getTokenHash()->equals($restoredDomain->getTokenHash()));
        self::assertTrue($domainToken->getAccountUlid()->equals($restoredDomain->getAccountUlid()));
        self::assertTrue($domainToken->getAccountType()->equals($restoredDomain->getAccountType()));
        self::assertTrue($domainToken->getExpiresAt()->equals($restoredDomain->getExpiresAt()));
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainToken = RefreshTokenMother::createWithData();
        $ormToken = new OrmRefreshToken();

        $this->mapper->mapToExistingOrm($domainToken, $ormToken);

        self::assertNull($ormToken->id);
        self::assertNull($ormToken->token);
        self::assertNull($ormToken->accountUlid);
        self::assertNull($ormToken->accountType);
        self::assertNull($ormToken->expiresAt);
    }
}
