<?php

declare(strict_types=1);

namespace App\Tests\IdentityAccess\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity\OrmUserAccount;
use App\IdentityAccess\Infrastructure\Persistence\Doctrine\Mapper\UserAccountMapper;
use App\Tests\IdentityAccess\Support\Traits\IdentityAccessEntityManagerTrait;
use App\Tests\IdentityAccess\Support\UserAccountMother;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class UserAccountMapperTest extends KernelTestCase
{
    use IdentityAccessEntityManagerTrait;

    private EntityManagerInterface $em;
    private UserAccountMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getIdentityAccessEntityManager();
        $this->mapper = new UserAccountMapper();
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainUser = UserAccountMother::createWithData(email: 'test.user.mapper@example.com');

        $ormUser = $this->mapper->toDoctrineOrm($domainUser);

        self::assertNull($ormUser->id);
        self::assertSame($domainUser->getUlid()->value(), $ormUser->ulid);
        self::assertSame($domainUser->getEmail()->value(), $ormUser->email);
        self::assertSame($domainUser->getPasswordHash()->value(), $ormUser->passwordHash);
        self::assertIsArray($ormUser->roles);
        self::assertSame($domainUser->getRoles()->toStrings(), $ormUser->roles);

        $this->em->persist($ormUser);
        $this->em->flush();

        $generatedId = $ormUser->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmUserAccount::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainUser->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainUser->getEmail()->equals($restoredDomain->getEmail()));
        self::assertTrue($domainUser->getPasswordHash()->equals($restoredDomain->getPasswordHash()));
        self::assertIsArray($restoredDomain->getRoles()->toStrings());
        self::assertTrue($domainUser->getRoles()->equals($restoredDomain->getRoles()));
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainUser = UserAccountMother::createWithData(roles: ['ROLE_USER']);
        $ormUser = new OrmUserAccount();
        $ormUser->roles = ['ROLE_OLD'];

        $this->mapper->mapToExistingOrm($domainUser, $ormUser);

        self::assertEquals($domainUser->getRoles()->toStrings(), $ormUser->roles);
        self::assertNull($ormUser->id);
        self::assertNull($ormUser->ulid);
        self::assertNull($ormUser->email);
        self::assertNull($ormUser->passwordHash);
    }
}
