services:
  catalog.proxy_reference_provider:
    class: App\Shared\Infrastructure\Persistence\Doctrine\Provider\DoctrineProxyReferenceProvider
    arguments:
      $em: '@doctrine.orm.catalog_entity_manager'

  App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\CategoryMapper:
    arguments:
      $referenceProvider: '@catalog.proxy_reference_provider'

  App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\ProductMapper:
    arguments:
      $referenceProvider: '@catalog.proxy_reference_provider'

  App\Catalog\Domain\Service\CategoryValidatorInterface: '@App\Catalog\Domain\Service\CategoryValidator'
  App\Catalog\Domain\Service\CategoryManagerInterface: '@App\Catalog\Domain\Service\CategoryManager'

  App\Catalog\Domain\Factory\Contract\AttributeFactoryInterface: '@App\Catalog\Domain\Factory\AttributeFactory'
  App\Catalog\Domain\Repository\AttributeReadRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\AttributeReadRepository'
  App\Catalog\Domain\Repository\AttributeWriteRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\AttributeWriteRepository'

  App\Catalog\Domain\Factory\Contract\CategoryFactoryInterface: '@App\Catalog\Domain\Factory\CategoryFactory'
  App\Catalog\Domain\Repository\CategoryReadRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\CategoryReadRepository'
  App\Catalog\Domain\Repository\CategoryWriteRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\CategoryWriteRepository'

  App\Catalog\Domain\Repository\ProductReadRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\ProductReadRepository'
  App\Catalog\Domain\Repository\ProductWriteRepositoryInterface: '@App\Catalog\Infrastructure\Persistence\Doctrine\Repository\ProductWriteRepository'
