parameters:

services:
  App\Customer\Domain\Repository\CustomerProfileReadRepositoryInterface: '@App\Customer\Infrastructure\Persistence\Doctrine\Repository\CustomerProfileReadRepository'
  App\Customer\Domain\Repository\CustomerProfileWriteRepositoryInterface: '@App\Customer\Infrastructure\Persistence\Doctrine\Repository\CustomerProfileWriteRepository'
