parameters:
  email_sender.max_attempts: '%env(int:EMAIL_OUTBOX_MAX_ATTEMPTS)%'
  email_sender.retry_strategy: 'quadratic'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\EmailSender\Domain\Service\OutboxRetryPolicy:
    arguments:
      $maxAttempts: '%email_sender.max_attempts%'

  App\EmailSender\Infrastructure\Service\OutboxEmailFactory:
    arguments:
      $defaultFrom: '%env(MAIL_FROM_NAME)%'
      $defaultFromName: '%env(MAIL_FROM_ADDRESS)%'
      $defaultMailDriver: "%env(MAIL_DRIVER)%"

  App\EmailSender\Domain\Repository\OutboxEmailReadRepositoryInterface: '@App\EmailSender\Infrastructure\Persistence\Doctrine\Repository\OutboxEmailReadRepository'
  App\EmailSender\Domain\Repository\OutboxEmailWriteRepositoryInterface: '@App\EmailSender\Infrastructure\Persistence\Doctrine\Repository\OutboxEmailWriteRepository'
  App\EmailSender\Domain\Service\MailerServiceInterface: '@App\EmailSender\Infrastructure\Service\MailerService'
  App\EmailSender\Domain\Service\OutboxEmailFactoryInterface: '@App\EmailSender\Infrastructure\Service\OutboxEmailFactory'
