parameters:
  identity_access.jwt.ttl: '%env(int:JWT_TTL)%'
  identity_access.refresh_token.ttl: '%env(int:REFRESH_TOKEN_TTL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  identity_access.token_blacklist.redis_adapter:
    parent: 'cache.adapter.redis'
    tags:
      - { name: 'cache.pool', namespace: 'jwt_bl' }

  App\IdentityAccess\Application\Service\RefreshTokenService:
    arguments:
      $ttl: '%identity_access.refresh_token.ttl%'

  App\IdentityAccess\Infrastructure\Security\Jwt\JwtGenerator:
    arguments:
      $appName: '%app.name%'
      $ttl: '%identity_access.jwt.ttl%'

  Lcobucci\JWT\Configuration:
    factory: [ 'App\IdentityAccess\Infrastructure\Security\Jwt\JwtConfigFactory', 'create' ]
    arguments:
      $privateKey: '%env(base64:JWT_PRIVATE_KEY_BASE64)%'
      $publicKey: '%env(base64:JWT_PUBLIC_KEY_BASE64)%'
      $passphrase: '%env(JWT_PASSPHRASE)%'

  App\IdentityAccess\Infrastructure\Security\Blacklist\RedisAccessTokenBlacklist:
    arguments:
      $identityAccessTokenBlacklistPool: '@identity_access.token_blacklist'

  App\IdentityAccess\Application\Security\CurrentAccessTokenContextInterface: '@App\IdentityAccess\Infrastructure\Security\Context\CurrentAccessTokenContext'
  App\IdentityAccess\Infrastructure\Security\Context\CurrentAccessTokenContext:
    tags:
      - { name: 'kernel.reset', method: 'reset' }

  App\IdentityAccess\Application\Security\TokenGeneratorInterface: '@App\IdentityAccess\Infrastructure\Security\Jwt\JwtGenerator'
  App\IdentityAccess\Domain\Service\PasswordGeneratorInterface: '@App\IdentityAccess\Infrastructure\Service\NativeRandomStringGenerator'
  App\IdentityAccess\Domain\Service\RandomTokenGeneratorInterface: '@App\IdentityAccess\Infrastructure\Service\NativeRandomStringGenerator'

  App\IdentityAccess\Application\Service\OAuth2TokenServiceInterface: '@App\IdentityAccess\Application\Service\OAuth2TokenService'
  App\IdentityAccess\Application\Service\RefreshTokenServiceInterface: '@App\IdentityAccess\Application\Service\RefreshTokenService'

  App\IdentityAccess\Domain\Service\AdminAccountFactoryInterface: '@App\IdentityAccess\Infrastructure\Service\AdminAccountFactory'
  App\IdentityAccess\Domain\Repository\AdminAccountReadRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\AdminAccountReadRepository'
  App\IdentityAccess\Domain\Repository\AdminAccountWriteRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\AdminAccountWriteRepository'

  App\IdentityAccess\Domain\Service\ModuleAccountFactoryInterface: '@App\IdentityAccess\Infrastructure\Service\ModuleAccountFactory'
  App\IdentityAccess\Domain\Repository\ModuleAccountReadRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\ModuleAccountReadRepository'
  App\IdentityAccess\Domain\Repository\ModuleAccountWriteRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\ModuleAccountWriteRepository'

  App\IdentityAccess\Domain\Service\RefreshTokenFactoryInterface: '@App\IdentityAccess\Infrastructure\Service\RefreshTokenFactory'
  App\IdentityAccess\Domain\Repository\RefreshTokenReadRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\RefreshTokenReadRepository'
  App\IdentityAccess\Domain\Repository\RefreshTokenWriteRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\RefreshTokenWriteRepository'

  App\IdentityAccess\Domain\Service\UserAccountFactoryInterface: '@App\IdentityAccess\Infrastructure\Service\UserAccountFactory'
  App\IdentityAccess\Domain\Repository\UserAccountReadRepositoryInterface: '@App\IdentityAccess\Infrastructure\Persistence\Doctrine\Repository\UserAccountReadRepository'

  App\IdentityAccess\Domain\Service\PasswordHasherInterface: '@App\IdentityAccess\Infrastructure\Security\Hasher\PasswordHasherService'
  App\IdentityAccess\Domain\Service\TokenHasherInterface: '@App\IdentityAccess\Infrastructure\Security\Hasher\TokenHasherService'

  App\Shared\Application\Security\AuthEntityContextInterface: '@App\IdentityAccess\Infrastructure\Security\Bridge\SymfonyAuthEntityContext'
