identity_access.public.api.v1:
  resource:
    path: ../ApiVersion1/Controller/
    namespace: App\IdentityAccess\Presentation\Http\ApiVersion1\Controller
  type: attribute
  prefix: /api/v1/identity-access

identity_access.admin.api.v1:
  resource:
    path: ../AdminApiVersion1/Controller/
    namespace: App\IdentityAccess\Presentation\Http\AdminApiVersion1\Controller
  type: attribute
  prefix: /admin/api/v1/identity-access

identity_access.internal.api.v1:
  resource:
    path: ../InternalApiVersion1/Controller/
    namespace: App\IdentityAccess\Presentation\Http\InternalApiVersion1\Controller
  type: attribute
  prefix: /internal/api/v1/identity-access

