<?php

declare(strict_types=1);

namespace App\Tests\Catalog\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\Catalog\Domain\Entity\Attribute;
use App\Catalog\Domain\Enum\Attribute\TypeEnum;
use App\Catalog\Domain\ValueObject\AttributeOption\Metadata\DimensionMetadata;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmAttribute;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmAttributeOptionTranslation;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmAttributeTranslation;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\AttributeMapper;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\AttributeOptionMapper;
use App\Catalog\Infrastructure\Persistence\Doctrine\Normalizer\AttributeOptionMetadataNormalizer;
use App\Tests\Catalog\Support\AttributeMother;
use App\Tests\Catalog\Support\Traits\AttributeFactoryTrait;
use App\Tests\Catalog\Support\Traits\CatalogEntityManagerTrait;
use App\Tests\Shared\Support\Traits\ValueObjectAssertionTrait;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class AttributeMapperTest extends KernelTestCase
{
    use AttributeFactoryTrait;
    use CatalogEntityManagerTrait;
    use ValueObjectAssertionTrait;

    private EntityManagerInterface $em;
    private AttributeMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getCatalogEntityManager();
        $this->mapper = new AttributeMapper(
            attributeOptionMapper: new AttributeOptionMapper(
                normalizer: new AttributeOptionMetadataNormalizer(),
            ),
        );
    }

    #[DataProvider('attributeDataProvider')]
    public function testItSuccessfullyPerformsRoundTrip(TypeEnum $type, bool $initializeOptions = true): void
    {
        $domainAttribute = $this->getAttributeMother()->create(type: $type);

        $ormAttribute = $this->mapper->toDoctrineOrm($domainAttribute);

        self::assertNull($ormAttribute->id);
        self::assertSame($domainAttribute->getUlid()->value(), $ormAttribute->ulid);
        self::assertSame($domainAttribute->getCode()->value(), $ormAttribute->code);
        self::assertSame($domainAttribute->getType()->value(), $ormAttribute->type);
        $this->assertOrmTranslationsMatch($domainAttribute, $ormAttribute);
        self::assertSame($domainAttribute->getVersion()->value(), $ormAttribute->version);
        self::assertSame($domainAttribute->getCreatedBy()->value(), $ormAttribute->createdBy);
        $this->assertOrmOptionsMatch($domainAttribute, $ormAttribute);
        self::assertSame($domainAttribute->getUpdatedBy()?->value(), $ormAttribute->updatedBy);

        $this->em->persist($ormAttribute);
        $this->em->flush();

        $generatedId = $ormAttribute->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmAttribute::class, $generatedId);
        self::assertNotNull($loadedOrm);
        if ($initializeOptions) {
            // because we have lazy loading options in domain
            $loadedOrm->options->initialize();
        }

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainAttribute->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainAttribute->getCode()->equals($restoredDomain->getCode()));
        self::assertTrue($domainAttribute->getType()->equals($restoredDomain->getType()));
        self::assertTrue($domainAttribute->getTranslations()->equals($restoredDomain->getTranslations()));
        self::assertTrue($domainAttribute->getCreatedBy()->equals($restoredDomain->getCreatedBy()));
        $this->assertRestoredOptionsMatch($domainAttribute, $restoredDomain, $initializeOptions);
        $this->assertVoEqualsOrNull($domainAttribute->getUpdatedBy(), $restoredDomain->getUpdatedBy());
    }

    public static function attributeDataProvider(): iterable
    {
        yield 'without metadata and options' => [TypeEnum::String];
        yield 'with options and no metadata' => [TypeEnum::MultiSelect];
        yield 'with metadata and option' => [TypeEnum::Dimension];
        yield 'without initializing options' => [TypeEnum::Select, false];
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainAttribute = AttributeMother::createWithData(
            code: 'new-test-code',
            type: TypeEnum::Text,
            translations: ['en' => ['name' => 'New name']],
            updatedByUlid: '01KHVRCA679BJ6PBXX5N3G6RR5'
        );

        $ormAttribute = new OrmAttribute();
        $ormAttribute->code = 'old-test-code';
        $ormAttribute->type = TypeEnum::String;
        $ormAttribute->updatedBy = 'old_ulid';

        $translation = new OrmAttributeTranslation();
        $translation->locale = 'en';
        $translation->name = 'Old name';
        $ormAttribute->translations->add($translation);

        $this->mapper->mapToExistingOrm($domainAttribute, $ormAttribute);

        self::assertSame($domainAttribute->getCode()->value(), $ormAttribute->code);
        self::assertSame($domainAttribute->getType()->value(), $ormAttribute->type);
        $this->assertOrmTranslationsMatch($domainAttribute, $ormAttribute);
        self::assertSame($domainAttribute->getUpdatedBy()->value(), $ormAttribute->updatedBy);
        self::assertNull($ormAttribute->id);
        self::assertNull($ormAttribute->ulid);
        self::assertNull($ormAttribute->version);
        self::assertNull($ormAttribute->createdBy);
    }

    private function assertOrmTranslationsMatch(Attribute $domain, OrmAttribute $orm): void
    {
        self::assertCount($domain->getTranslations()->count(), $orm->translations);

        $ormTranslations = [];
        foreach ($orm->translations as $ormT) {
            $ormTranslations[$ormT->locale] = $ormT;
        }

        foreach ($domain->getTranslations() as $locale => $domainTranslation) {
            $ormTranslation = $ormTranslations[$locale] ?? null;

            self::assertNotNull($ormTranslation, sprintf('Translation for %s locale not found in ORM', $locale));
            self::assertSame($domainTranslation->name, $ormTranslation->name);
        }
    }

    private function assertOrmOptionsMatch(Attribute $domain, OrmAttribute $orm): void
    {
        self::assertCount($domain->getOptions()->count(), $orm->options);

        $ormOptions = [];
        foreach ($orm->options as $ormOption) {
            $ormOptions[$ormOption->ulid] = $ormOption;
        }

        foreach ($domain->getOptions() as $domainOption) {
            $ormOption = $ormOptions[$domainOption->getUlid()->value()] ?? null;

            self::assertNotNull($ormOption, sprintf('Option with ulid %s not found in ORM', $domainOption->getUlid()));
            self::assertNull($ormOption->id);
            self::assertSame($domainOption->getCode()->value(), $ormOption->code);
            self::assertCount($domainOption->getTranslations()->count(), $ormOption->translations);
            foreach ($domainOption->getTranslations() as $locale => $domainTranslation) {
                $ormTranslation = $ormOption->translations->filter(
                    fn (OrmAttributeOptionTranslation $t) => $t->locale === $locale
                )->first();

                self::assertNotNull($ormTranslation, sprintf('Translation for %s locale not found in ORM', $locale));
                self::assertSame($domainTranslation->value, $ormTranslation->value);
            }
            self::assertSame($domainOption->isActive()->value(), $ormOption->isActive);
            self::assertSame($domainOption->getVersion()->value(), $ormOption->version);
            self::assertSame($domainOption->getCreatedBy()->value(), $ormOption->createdBy);
            if ($domain->getType()->is(TypeEnum::Dimension)) {
                self::assertNotNull($ormOption->valueJson);
                $domainMetadata = $domainOption->getMetadata();
                self::assertNotNull($domainMetadata);
                self::assertInstanceOf(DimensionMetadata::class, $domainMetadata);
                self::assertSame(['base_ratio' => $domainMetadata->getBaseRatio()], $ormOption->valueJson);
            } else {
                self::assertNull($ormOption->valueJson);
            }
            self::assertSame($domainOption->getUpdatedBy()?->value(), $ormOption->updatedBy);
        }
    }

    private function assertRestoredOptionsMatch(Attribute $domain, Attribute $restored, bool $initializedOptions): void
    {
        self::assertSame($initializedOptions, $restored->getOptions()->isInitialized());

        if (false === $initializedOptions) {
            self::assertCount(0, $restored->getOptions());

            return;
        }

        self::assertCount($domain->getOptions()->count(), $restored->getOptions());

        foreach ($domain->getOptions() as $domainOption) {
            $restoredOption = $restored->getOptions()->getByUlid($domainOption->getUlid());
            self::assertNotNull($restoredOption);
            self::assertNotNull($restoredOption->getId());
            self::assertTrue($domainOption->getCode()->equals($restoredOption->getCode()));
            self::assertTrue($domainOption->getTranslations()->equals($restoredOption->getTranslations()));
            self::assertTrue($domainOption->isActive()->equals($restoredOption->isActive()));
            self::assertTrue($domainOption->getVersion()->equals($restoredOption->getVersion()));
            self::assertTrue($domainOption->getCreatedBy()->equals($restoredOption->getCreatedBy()));
            $this->assertVoEqualsOrNull($domainOption->getMetadata(), $restoredOption->getMetadata());
            $this->assertVoEqualsOrNull($domainOption->getUpdatedBy(), $restoredOption->getUpdatedBy());
        }
    }
}
