<?php

declare(strict_types=1);

namespace App\Tests\Catalog\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\Catalog\Domain\Entity\Attribute;
use App\Catalog\Domain\Enum\Attribute\TypeEnum;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmAttribute;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmAttributeTranslation;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\AttributeMapper;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\AttributeOptionMapper;
use App\Catalog\Infrastructure\Persistence\Doctrine\Normalizer\AttributeOptionMetadataNormalizer;
use App\Tests\Catalog\Support\AttributeMother;
use App\Tests\Catalog\Support\Traits\CatalogEntityManagerTrait;
use App\Tests\Shared\Support\Traits\ValueObjectAssertionTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class AttributeMapperTest extends KernelTestCase
{
    use CatalogEntityManagerTrait;
    use ValueObjectAssertionTrait;

    private EntityManagerInterface $em;
    private AttributeMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getCatalogEntityManager();
        $this->mapper = new AttributeMapper(
            attributeOptionMapper: new AttributeOptionMapper(
                normalizer: new AttributeOptionMetadataNormalizer(),
            ),
        );
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainAttribute = AttributeMother::createWithData();

        $ormAttribute = $this->mapper->toDoctrineOrm($domainAttribute);

        self::assertNull($ormAttribute->id);
        self::assertSame($domainAttribute->getUlid()->value(), $ormAttribute->ulid);
        self::assertSame($domainAttribute->getCode()->value(), $ormAttribute->code);
        self::assertSame($domainAttribute->getType()->value(), $ormAttribute->type);
        $this->assertOrmTranslationsMatch($domainAttribute, $ormAttribute);
        self::assertSame($domainAttribute->getVersion()->value(), $ormAttribute->version);
        self::assertSame($domainAttribute->getCreatedBy()->value(), $ormAttribute->createdBy);
        self::assertSame($domainAttribute->getUpdatedBy()?->value(), $ormAttribute->updatedBy);

        $this->em->persist($ormAttribute);
        $this->em->flush();

        $generatedId = $ormAttribute->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmAttribute::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainAttribute->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainAttribute->getCode()->equals($restoredDomain->getCode()));
        self::assertTrue($domainAttribute->getType()->equals($restoredDomain->getType()));
        self::assertCount($domainAttribute->getTranslations()->count(), $restoredDomain->getTranslations());
        foreach ($domainAttribute->getTranslations() as $locale => $translation) {
            $restoredTranslation = $restoredDomain->getTranslations()->get($locale);
            self::assertNotNull($restoredTranslation);
            self::assertSame($translation->name, $restoredTranslation->name);
        }
        self::assertTrue($domainAttribute->getCreatedBy()->equals($restoredDomain->getCreatedBy()));
        $this->assertVoEqualsOrNull($domainAttribute->getUpdatedBy(), $restoredDomain->getUpdatedBy());
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainAttribute = AttributeMother::createWithData(
            code: 'new-test-code',
            type: TypeEnum::String,
            translations: ['en' => ['name' => 'New name']],
            updatedByUlid: '01KHVRCA679BJ6PBXX5N3G6RR5'
        );

        $ormAttribute = new OrmAttribute();
        $ormAttribute->code = 'old-test-code';
        $ormAttribute->type = TypeEnum::Integer;
        $ormAttribute->updatedBy = 'old_ulid';

        $translation = new OrmAttributeTranslation();
        $translation->locale = 'en';
        $translation->name = 'Old name';
        $ormAttribute->translations->add($translation);

        $this->mapper->mapToExistingOrm($domainAttribute, $ormAttribute);

        self::assertSame($domainAttribute->getCode()->value(), $ormAttribute->code);
        self::assertSame($domainAttribute->getType()->value(), $ormAttribute->type);
        $this->assertOrmTranslationsMatch($domainAttribute, $ormAttribute);
        self::assertSame($domainAttribute->getUpdatedBy()->value(), $ormAttribute->updatedBy);
        self::assertNull($ormAttribute->id);
        self::assertNull($ormAttribute->ulid);
        self::assertNull($ormAttribute->version);
        self::assertNull($ormAttribute->createdBy);
    }

    private function assertOrmTranslationsMatch(Attribute $domain, OrmAttribute $orm): void
    {
        self::assertCount($domain->getTranslations()->count(), $orm->translations);

        foreach ($domain->getTranslations() as $locale => $domainTranslation) {
            $ormTranslation = $orm->translations->filter(
                fn (OrmAttributeTranslation $t) => $t->locale === $locale
            )->first();

            self::assertNotNull($ormTranslation, sprintf('Translation for %s locale not found in ORM', $locale));
            self::assertSame($domainTranslation->name, $ormTranslation->name);
        }
    }
}
