<?php

declare(strict_types=1);

namespace App\Tests\Catalog\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\Catalog\Domain\Entity\Category;
use App\Catalog\Domain\Enum\Category\StatusEnum;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmCategory;
use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmCategoryTranslation;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\CategoryMapper;
use App\Shared\Domain\Service\Identity\UlidGeneratorInterface;
use App\Tests\Catalog\Support\CategoryMother;
use App\Tests\Catalog\Support\Traits\CatalogEntityManagerTrait;
use App\Tests\Shared\Support\Traits\ValueObjectAssertionTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class CategoryMapperTest extends KernelTestCase
{
    use CatalogEntityManagerTrait;
    use ValueObjectAssertionTrait;

    private EntityManagerInterface $em;
    private UlidGeneratorInterface $ulidGenerator;
    private CategoryMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getCatalogEntityManager();
        $this->ulidGenerator = self::getContainer()->get(UlidGeneratorInterface::class);
        $this->mapper = self::getContainer()->get(CategoryMapper::class);
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainCategory = CategoryMother::createWithData();

        $ormCategory = $this->mapper->toDoctrineOrm($domainCategory);

        self::assertNull($ormCategory->id);
        self::assertSame($domainCategory->getParentId()?->value(), $ormCategory->parent?->id);
        self::assertSame($domainCategory->getUlid()->value(), $ormCategory->ulid);
        self::assertSame($domainCategory->getPath()->value(), $ormCategory->path);
        self::assertSame($domainCategory->getSlug()->value(), $ormCategory->slug);
        self::assertSame($domainCategory->getSortOrder()->value(), $ormCategory->sortOrder);
        self::assertSame($domainCategory->getStatus()->value(), $ormCategory->status);
        $this->assertOrmTranslationsMatch($domainCategory, $ormCategory);
        self::assertSame($domainCategory->getVersion()->value(), $ormCategory->version);
        self::assertSame($domainCategory->getCreatedBy()->value(), $ormCategory->createdBy);
        self::assertSame($domainCategory->getUpdatedBy()?->value(), $ormCategory->updatedBy);

        $this->em->persist($ormCategory);
        $this->em->flush();

        $generatedId = $ormCategory->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $this->em->clear();

        $loadedOrm = $this->em->find(OrmCategory::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainCategory->getUlid()->equals($restoredDomain->getUlid()));
        $this->assertVoEqualsOrNull($domainCategory->getParentId(), $restoredDomain->getParentId());
        self::assertTrue($domainCategory->getPath()->equals($restoredDomain->getPath()));
        self::assertTrue($domainCategory->getSlug()->equals($restoredDomain->getSlug()));
        self::assertTrue($domainCategory->getSortOrder()->equals($restoredDomain->getSortOrder()));
        self::assertTrue($domainCategory->getStatus()->equals($restoredDomain->getStatus()));
        self::assertTrue($domainCategory->getTranslations()->equals($restoredDomain->getTranslations()));
        self::assertTrue($domainCategory->getVersion()->equals($restoredDomain->getVersion()));
        self::assertTrue($domainCategory->getCreatedBy()->equals($restoredDomain->getCreatedBy()));
        $this->assertVoEqualsOrNull($domainCategory->getUpdatedBy(), $restoredDomain->getUpdatedBy());
    }

    public function testItSuccessfullyPerformsRoundTripWithParent(): void
    {
        $parentDomain = CategoryMother::createWithData(
            ulid: $this->ulidGenerator->next(),
            path: '/parent-category',
            slug: 'parent-category'
        );
        $parentOrm = $this->mapper->toDoctrineOrm($parentDomain);
        $this->em->persist($parentOrm);
        $this->em->flush();

        $parentId = $parentOrm->id;
        self::assertNotNull($parentId);

        $childDomain = CategoryMother::createWithData(
            parentId: $parentId,
            path: '/parent-category/child-category',
            slug: 'child-category'
        );

        $childOrm = $this->mapper->toDoctrineOrm($childDomain);

        self::assertNotNull($childOrm->parent, 'The parent should be set on the child ORM entity');
        self::assertSame($parentId, $childOrm->parent->id);

        $this->em->persist($childOrm);
        $this->em->flush();
        $childId = $childOrm->id;

        $this->em->clear();

        $loadedChildOrm = $this->em->find(OrmCategory::class, $childId);
        self::assertNotNull($loadedChildOrm->parent);

        $restoredChildDomain = $this->mapper->fromDoctrineOrm($loadedChildOrm);

        self::assertNotNull($restoredChildDomain->getParentId());
        self::assertSame($parentId, $restoredChildDomain->getParentId()->value());
        self::assertTrue($childDomain->getSlug()->equals($restoredChildDomain->getSlug()));
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainCategory = CategoryMother::createWithData(
            path: '/new-path',
            slug: 'new-slug',
            sortOrder: 10,
            status: StatusEnum::Active,
            translations: ['en' => ['name' => 'New name', 'description' => 'New description']],
            updatedByUlid: '01KHVRCA679BJ6PBXX5N3G6RR5'
        );

        $ormCategory = new OrmCategory();
        $ormCategory->path = '/old-path';
        $ormCategory->slug = 'old-slug';
        $ormCategory->sortOrder = 5;
        $ormCategory->status = StatusEnum::Inactive;
        $ormCategory->updatedBy = 'old_ulid';

        $translation = new OrmCategoryTranslation();
        $translation->locale = 'en';
        $translation->name = 'Old name';
        $translation->description = 'Old description';
        $ormCategory->translations->add($translation);

        $this->mapper->mapToExistingOrm($domainCategory, $ormCategory);

        self::assertSame($domainCategory->getPath()->value(), $ormCategory->path);
        self::assertSame($domainCategory->getSlug()->value(), $ormCategory->slug);
        self::assertSame($domainCategory->getSortOrder()->value(), $ormCategory->sortOrder);
        self::assertSame($domainCategory->getStatus()->value(), $ormCategory->status);
        $this->assertOrmTranslationsMatch($domainCategory, $ormCategory);
        self::assertSame($domainCategory->getUpdatedBy()->value(), $ormCategory->updatedBy);
        self::assertNull($ormCategory->id);
        self::assertNull($ormCategory->ulid);
        self::assertNull($ormCategory->version);
        self::assertNull($ormCategory->createdBy);
    }

    public function testItCanRemoveParentOnUpdate(): void
    {
        $domainCategory = CategoryMother::createWithData();

        $ormCategory = new OrmCategory();
        $ormCategory->parent = new OrmCategory();

        $this->mapper->mapToExistingOrm($domainCategory, $ormCategory);

        self::assertNull($ormCategory->parent, 'Parent should be null in ORM');
    }

    private function assertOrmTranslationsMatch(Category $domain, OrmCategory $orm): void
    {
        self::assertCount($domain->getTranslations()->count(), $orm->translations);

        foreach ($domain->getTranslations() as $locale => $domainTranslation) {
            $ormTranslation = $orm->translations->filter(
                fn (OrmCategoryTranslation $t) => $t->locale === $locale
            )->first();

            self::assertNotNull($ormTranslation, sprintf('Translation for %s locale not found in ORM', $locale));
            self::assertSame($domainTranslation->name, $ormTranslation->name);
            self::assertSame($domainTranslation->description, $ormTranslation->description);
        }
    }
}
