<?php

declare(strict_types=1);

namespace App\Tests\Catalog\Integration\Infrastructure\Persistence\Doctrine\Mapper;

use App\Catalog\Infrastructure\Persistence\Doctrine\Entity\OrmTemporaryImage;
use App\Catalog\Infrastructure\Persistence\Doctrine\Mapper\TemporaryImageMapper;
use App\Tests\Catalog\Support\TemporaryImageMother;
use App\Tests\Catalog\Support\Traits\CatalogEntityManagerTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class TemporaryImageMapperTest extends KernelTestCase
{
    use CatalogEntityManagerTrait;

    private EntityManagerInterface $em;
    private TemporaryImageMapper $mapper;

    protected function setUp(): void
    {
        self::bootKernel();

        $this->em = $this->getEntityManager();
        $this->mapper = new TemporaryImageMapper();
    }

    public function testItSuccessfullyPerformsRoundTrip(): void
    {
        $domainTemporaryImage = TemporaryImageMother::createWithData();

        $ormTemporaryImage = $this->mapper->toDoctrineOrm($domainTemporaryImage);

        self::assertNull($ormTemporaryImage->id);

        self::assertSame($domainTemporaryImage->getUlid()->value(), $ormTemporaryImage->ulid);
        self::assertSame($domainTemporaryImage->getPath()->value(), $ormTemporaryImage->path);
        self::assertSame($domainTemporaryImage->getContext()->value(), $ormTemporaryImage->context);

        $this->em->persist($ormTemporaryImage);
        $this->em->flush();

        $generatedId = $ormTemporaryImage->id;
        self::assertNotNull($generatedId, 'The ID must be generated by the database');

        $loadedOrm = $this->em->find(OrmTemporaryImage::class, $generatedId);
        self::assertNotNull($loadedOrm);

        $restoredDomain = $this->mapper->fromDoctrineOrm($loadedOrm);

        self::assertSame($generatedId, $restoredDomain->getId()?->value());
        self::assertTrue($domainTemporaryImage->getUlid()->equals($restoredDomain->getUlid()));
        self::assertTrue($domainTemporaryImage->getPath()->equals($restoredDomain->getPath()));
        self::assertTrue($domainTemporaryImage->getContext()->equals($restoredDomain->getContext()));
    }

    public function testItUpdatesExistingOrmEntity(): void
    {
        $domainTemporaryImage = TemporaryImageMother::createWithData();

        $ormTemporaryImage = new OrmTemporaryImage();

        $this->mapper->mapToExistingOrm($domainTemporaryImage, $ormTemporaryImage);

        self::assertNull($ormTemporaryImage->id);
        self::assertNull($ormTemporaryImage->ulid);
        self::assertNull($ormTemporaryImage->path);
        self::assertNull($ormTemporaryImage->context);
    }
}
