app_shared_api:
  resource: '../src/Shared/Presentation/Http/config/routes.yaml'

customer_api:
  resource: '../src/Customer/Presentation/Http/config/routes.yaml'

identity_access_api:
  resource: '../src/IdentityAccess/Presentation/Http/config/routes.yaml'

kernel:
  resource:
    path: ../src/Shared/Infrastructure/
    namespace: App\Shared\Infrastructure
  type: attribute
