catalog:
  resource: '../src/Catalog/Presentation/Http/config/routes.yaml'

customer_routes:
  resource: '../src/Customer/Presentation/Http/config/routes.yaml'

identity_access_routes:
  resource: '../src/IdentityAccess/Presentation/Http/config/routes.yaml'

kernel:
  resource: '../src/Shared/Presentation/Http/config/routes.yaml'
