app_shared_api_v1:
  resource:
    path: ../src/Shared/Presentation/ApiVersion1/Controller/
    namespace: App\Shared\Presentation\ApiVersion1\Controller
  type: attribute

users_api_v1:
  resource: '../src/Users/Presentation/config/routes.yaml'

identity_access_api_v1:
  resource: '../src/IdentityAccess/Presentation/config/routes.yaml'

kernel:
  resource:
    path: ../src/Shared/Infrastructure/
    namespace: App\Shared\Infrastructure
  type: attribute
