<?php

declare(strict_types=1);

namespace App\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260118123351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user account table for identity access module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE identity_access_user_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            email VARCHAR(256) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            roles JSONB NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25FF72AEC288C859 ON identity_access_user_accounts (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25FF72AEE7927C74 ON identity_access_user_accounts (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_access_user_accounts');
    }
}
