<?php

declare(strict_types=1);

namespace App\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260118124049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create module account table for identity access module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE module_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            client_id VARCHAR(255) NOT NULL,
            client_secret VARCHAR(255) NOT NULL,
            scopes JSONB NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_module_accounts_ulid ON module_accounts (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_module_accounts_client_id ON module_accounts (client_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE module_accounts');
    }
}
