<?php

declare(strict_types=1);

namespace App\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260213132636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create admin account table for identity access module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE admin_account_status AS ENUM ('active', 'inactive', 'blocked', 'deleted', 'draft', 'on_vacation')");

        $this->addSql(
            'CREATE TABLE admin_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            email VARCHAR(256) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            roles JSONB NOT NULL,
            status admin_account_status NOT NULL,
            password_changed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_accounts_ulid ON admin_accounts (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_accounts_email ON admin_accounts (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_accounts');

        $this->addSql('DROP TYPE IF EXISTS admin_account_status');
    }
}
