<?php

declare(strict_types=1);

namespace App\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260118124301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create refresh token table for identity access module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE refresh_token_account_type AS ENUM ('user', 'module')");

        $this->addSql(
            'CREATE TABLE identity_access_refresh_tokens (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            token VARCHAR(255) NOT NULL,
            account_ulid UUID NOT NULL,
            account_type refresh_token_account_type NOT NULL,
            expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_75AD3CC55F37A13B ON identity_access_refresh_tokens (token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_access_refresh_tokens');
    }
}
