<?php

declare(strict_types=1);

namespace App\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260127191154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create identity access messages table for identity access module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE identity_access_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            body TEXT NOT NULL,
            headers TEXT NOT NULL,
            queue_name VARCHAR(190) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE INDEX idx_message_queue_name ON identity_access_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_message_available_at ON identity_access_messages (available_at)');
        $this->addSql('CREATE INDEX idx_message_delivered_at ON identity_access_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE identity_access_messages');
    }
}
