server {
  listen 80;
  listen 443 ssl;
  http2  on;

  server_name {{ sources_domain }};
  root /var/www/public;

  ssl_certificate /etc/nginx/ssl/cert.crt;
  ssl_certificate_key /etc/nginx/ssl/cert.key;

  error_log  stderr warn;
  access_log  /dev/stdout main;

  location ^~ /images/ {
    alias /var/www/storage/app/public/images/;
    try_files $uri =404;
    access_log off;
    expires 30d;
  }

  location ^~ /vendor/ {
    root /var/www/public;
    try_files $uri =404;
    access_log off;
    expires 30d;
  }

  location ^~ /emails/ {
    root /var/www/public;
    try_files $uri =404;
    access_log off;
    expires 30d;
  }

  location ~ /\. {
    deny all;
  }
}
