<?php

declare(strict_types=1);

namespace App\Customer\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260130141605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create customer profiles table for customer module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE customer_profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_ulid UUID NOT NULL,
            first_name VARCHAR(64) DEFAULT NULL,
            last_name VARCHAR(64) DEFAULT NULL,
            phone_number VARCHAR(20) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_profile_user_ulid ON customer_profiles (user_ulid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE customer_profiles');
    }
}
