<?php

declare(strict_types=1);

namespace App\Catalog\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260212160551 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create attributes, attribute translations, attribute options, attribute option translations tables for catalog module';
    }

    public function up(Schema $schema): void
    {
        $attributeTypes = [
            'string',
            'text',
            'integer',
            'float',
            'boolean',
            'select',
            'multiselect',
            'color',
            'date',
            'url',
            'dimension',
            'image',
        ];

        $this->addSql(sprintf(
            'CREATE TYPE attribute_type AS ENUM (%s)',
            implode(', ', array_map(fn (string $t) => "'{$t}'", $attributeTypes))
        ));

        $this->addSql(
            'CREATE TABLE attributes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            code VARCHAR(50) NOT NULL,
            type attribute_type NOT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attributes_ulid ON attributes (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attributes_code ON attributes (code)');

        $this->addSql(
            'CREATE TABLE attribute_translations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            locale VARCHAR(7) NOT NULL,
            name VARCHAR(255) NOT NULL,
            attribute_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_translations_attribute_id_locale ON attribute_translations (attribute_id, locale)');

        $this->addSql(
            'CREATE TABLE attribute_options (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            code VARCHAR(50) NOT NULL,
            is_active BOOLEAN NOT NULL,
            value_json JSONB DEFAULT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            attribute_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_options_ulid ON attribute_options (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_options_attribute_id_code ON attribute_options (attribute_id, code)');

        $this->addSql(
            'CREATE TABLE attribute_option_translations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            locale VARCHAR(7) NOT NULL,
            value VARCHAR(255) NOT NULL,
            option_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_option_translations_option_id_locale ON attribute_option_translations (option_id, locale)');

        $this->addSql(
            'ALTER TABLE attribute_translations
            ADD CONSTRAINT fk_attribute_translations_attribute_id
            FOREIGN KEY (attribute_id) REFERENCES attributes (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE attribute_options
            ADD CONSTRAINT fk_attribute_options_attribute_id
            FOREIGN KEY (attribute_id) REFERENCES attributes (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE attribute_option_translations
            ADD CONSTRAINT fk_attribute_option_translations_option_id
            FOREIGN KEY (option_id) REFERENCES attribute_options (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attribute_option_translations DROP CONSTRAINT fk_attribute_option_translations_option_id');
        $this->addSql('ALTER TABLE attribute_options DROP CONSTRAINT fk_attribute_options_attribute_id');
        $this->addSql('ALTER TABLE attribute_translations DROP CONSTRAINT fk_attribute_translations_attribute_id');

        $this->addSql('DROP TABLE attribute_option_translations');
        $this->addSql('DROP TABLE attribute_options');
        $this->addSql('DROP TABLE attribute_translations');
        $this->addSql('DROP TABLE attributes');

        $this->addSql('DROP TYPE IF EXISTS attribute_type');
    }
}
