<?php

declare(strict_types=1);

namespace App\Catalog\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260212161250 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create categories and category translations tables for catalog module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE category_status AS ENUM ('active', 'inactive')");

        $this->addSql(
            'CREATE TABLE categories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            path VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            sort_order INT NOT NULL,
            status category_status NOT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            parent_id BIGINT DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE INDEX idx_categories_parent_id ON categories (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_categories_ulid ON categories (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_categories_slug ON categories (slug)');

        $this->addSql(
            'CREATE TABLE category_translations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            locale VARCHAR(7) NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT DEFAULT NULL,
            category_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_category_translations_category_id_locale ON category_translations (category_id, locale)');

        $this->addSql('ALTER TABLE categories ADD CONSTRAINT fk_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_translations ADD CONSTRAINT fk_category_translations_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE category_translations DROP CONSTRAINT fk_category_translations_category_id');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT fk_categories_parent_id');

        $this->addSql('DROP TABLE category_translations');
        $this->addSql('DROP TABLE categories');

        $this->addSql('DROP TYPE IF EXISTS category_status');
    }
}
