<?php

declare(strict_types=1);

namespace App\Catalog\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260212170526 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products, product prices, product translations, product categories, product attributes values, product images tables for catalog module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE product_status AS ENUM ('draft', 'active', 'archived')");
        $this->addSql("CREATE TYPE product_price_type AS ENUM ('regular', 'sale', 'cost')");
        $this->addSql("CREATE TYPE product_price_currency AS ENUM ('UAH', 'USD')");
        $this->addSql("CREATE TYPE product_price_tax_type AS ENUM ('percentage', 'fixed')");

        $this->addSql(
            'CREATE TABLE products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            sku VARCHAR(50) NOT NULL,
            status product_status NOT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_products_ulid ON products (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_products_sku ON products (sku)');

        $this->addSql(
            'CREATE TABLE product_prices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            amount BIGINT NOT NULL,
            currency product_price_currency NOT NULL,
            type product_price_type NOT NULL,
            tax_value NUMERIC(10, 2) DEFAULT NULL,
            tax_type product_price_tax_type DEFAULT NULL,
            tax_included BOOLEAN NOT NULL,
            valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            product_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE INDEX idx_product_prices_product_id_type_currency ON product_prices (product_id, type, currency)');

        $this->addSql(
            'CREATE TABLE product_translations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            locale VARCHAR(7) NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT DEFAULT NULL,
            product_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_product_translations_product_id_locale ON product_translations (product_id, locale)');

        $this->addSql(
            'CREATE TABLE product_categories (
            product_id BIGINT NOT NULL,
            category_id BIGINT NOT NULL,
            PRIMARY KEY (product_id, category_id)
        )'
        );
        $this->addSql('CREATE INDEX idx_product_categories_product_id ON product_categories (product_id)');
        $this->addSql('CREATE INDEX idx_product_categories_category_id ON product_categories (category_id)');

        $this->addSql(
            'CREATE TABLE product_attribute_values (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            product_id BIGINT NOT NULL,
            attribute_id BIGINT NOT NULL,
            option_id BIGINT DEFAULT NULL,
            value_json JSONB DEFAULT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE INDEX idx_product_attribute_values_product_id ON product_attribute_values (product_id)');
        $this->addSql('CREATE INDEX idx_product_attribute_values_attribute_id ON product_attribute_values (attribute_id)');
        $this->addSql('CREATE INDEX idx_product_attribute_values_option_id ON product_attribute_values (option_id)');

        $this->addSql(
            'CREATE TABLE product_images (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            path VARCHAR(511) NOT NULL,
            sort_order INT NOT NULL,
            is_main BOOLEAN NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            product_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE INDEX idx_product_images_product_id ON product_images (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_images_ulid ON product_images (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_images_main ON product_images (product_id) WHERE (is_main = true)');

        $this->addSql(
            'ALTER TABLE product_prices
            ADD CONSTRAINT fk_product_prices_product_id
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_translations
            ADD CONSTRAINT fk_product_translations_product_id
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_categories
            ADD CONSTRAINT fk_product_categories_product_id
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_categories
            ADD CONSTRAINT fk_product_categories_category_id
            FOREIGN KEY (category_id) REFERENCES categories (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_attribute_values
            ADD CONSTRAINT fk_product_attribute_values_product_id
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_attribute_values
            ADD CONSTRAINT fk_product_attribute_values_attribute_id
            FOREIGN KEY (attribute_id) REFERENCES attributes (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_attribute_values
            ADD CONSTRAINT fk_product_attribute_values_option_id
            FOREIGN KEY (option_id) REFERENCES attribute_options (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql(
            'ALTER TABLE product_images
            ADD CONSTRAINT fk_product_images_product_id
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT fk_product_images_product_id');
        $this->addSql('ALTER TABLE product_attribute_values DROP CONSTRAINT fk_product_attribute_values_option_id');
        $this->addSql('ALTER TABLE product_attribute_values DROP CONSTRAINT fk_product_attribute_values_attribute_id');
        $this->addSql('ALTER TABLE product_attribute_values DROP CONSTRAINT fk_product_attribute_values_product_id');
        $this->addSql('ALTER TABLE product_categories DROP CONSTRAINT fk_product_categories_category_id');
        $this->addSql('ALTER TABLE product_categories DROP CONSTRAINT fk_product_categories_product_id');
        $this->addSql('ALTER TABLE product_translations DROP CONSTRAINT fk_product_translations_product_id');
        $this->addSql('ALTER TABLE product_prices DROP CONSTRAINT fk_product_prices_product_id');

        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE product_attribute_values');
        $this->addSql('DROP TABLE product_translations');
        $this->addSql('DROP TABLE product_categories');
        $this->addSql('DROP TABLE product_prices');
        $this->addSql('DROP TABLE products');

        $this->addSql('DROP TYPE IF EXISTS product_status');
        $this->addSql('DROP TYPE IF EXISTS product_price_type');
        $this->addSql('DROP TYPE IF EXISTS product_price_currency');
        $this->addSql('DROP TYPE IF EXISTS product_price_tax_type');
    }
}
