<?php

declare(strict_types=1);

namespace App\Catalog\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260212160551 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create attributes and attribute translations tables for catalog module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE attribute_type AS ENUM ('string', 'int', 'boolean', 'select')");

        $this->addSql(
            'CREATE TABLE attributes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            code VARCHAR(50) NOT NULL,
            type attribute_type NOT NULL,
            version INT DEFAULT 1 NOT NULL,
            created_by UUID NOT NULL,
            updated_by UUID DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attributes_ulid ON attributes (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attributes_code ON attributes (code)');

        $this->addSql(
            'CREATE TABLE attribute_translations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            locale VARCHAR(7) NOT NULL,
            name VARCHAR(255) NOT NULL,
            attribute_id BIGINT NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_translations_attribute_id_locale ON attribute_translations (attribute_id, locale)');

        $this->addSql('ALTER TABLE attribute_translations ADD CONSTRAINT fk_attribute_translations_attribute_id FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attribute_translations DROP CONSTRAINT fk_attribute_translations_attribute_id');
        $this->addSql('DROP TABLE attribute_translations');
        $this->addSql('DROP TABLE attributes');

        $this->addSql('DROP TYPE attribute_type');
    }
}
