<?php

declare(strict_types=1);

namespace App\Catalog\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260310072315 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create temporary images table for catalog module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE temporary_image_context AS ENUM ('product_main', 'category_icon')");

        $this->addSql(
            'CREATE TABLE temporary_images (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ulid UUID NOT NULL,
            path VARCHAR(511) NOT NULL,
            context temporary_image_context NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_temporary_images_ulid ON temporary_images (ulid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE temporary_images');

        $this->addSql('DROP TYPE IF EXISTS temporary_image_context');
    }
}
